export const ACTIONS = {
	SET_TEST_STATE : "SET_TEST_STATE",
	SET_APP_THEME: "SET_APP_THEME",

	SET_USER_NOTE_DATA: "SET_APP_NOTE_DATA",
	SET_USER_SIGNED_IN : "SET_USER_SIGNED_IN",
	SET_USER_SETTING : "SET_USER_SETTING"
}
